name = "yilia"
description = "A classic blog theme"
license = "MIT"
homepage = "https://github.com/Keats/zola-hyde"
# The minimum version of Zola required
min_version = "0.4.0"
# An optional live demo URL
demo = ""

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
theme_root = "https://example.com"

theme_author = "作者"

theme_avatar = "头像"

theme_subtitle = "副标题"

theme_menu = [
    {url = "123", name="ce"}
]

theme_smart_menu = [
    {url = "123", name="ce"}
]

theme_subnav = [1,2,3]

# The theme author info: you!
[author]
name = "Vincent Prouillet"
homepage = "https://vincent.is"

# If this is porting a theme from another static site engine, provide
# the info of the original author here
[original]
author =  "mdo"
homepage = "http://markdotto.com/"
repo = "https://www.github.com/mdo/hyde"